apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-data-provider
  namespace: gatekeeper-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: external-data-provider
  template:
    metadata:
      labels:
        run: external-data-provider
    spec:
      containers:
        - args:
            - --cert-dir=/certs
            - --client-ca-file=/tmp/gatekeeper/ca.crt
            - --port=8090
          image: arnobkumarsaha/external-data-provider:dev
          imagePullPolicy: IfNotPresent
          name: external-data-provider
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8090
          volumeMounts:
            - mountPath: /tmp/gatekeeper
              name: gatekeeper-ca-cert
              readOnly: true
      volumes:
        - name: gatekeeper-ca-cert
          secret:
            defaultMode: 420
            items:
              - key: ca.crt
                path: ca.crt
            secretName: gatekeeper-webhook-server-cert
---
apiVersion: v1
kind: Service
metadata:
  name: external-data-provider
  namespace: gatekeeper-system
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    run: external-data-provider
  type: ClusterIP
---
apiVersion: externaldata.gatekeeper.sh/v1beta1
kind: Provider
metadata:
  name: external-data-provider
spec:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSVENDQWkyZ0F3SUJBZ0lVWEVYSjB1SzdMNDVSQ0RBUTdKeEZPU25iV2djd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01qRVRNQkVHQTFVRUNnd0tSMkYwWld0bFpYQmxjakViTUJrR0ExVUVBd3dTUjJGMFpXdGxaWEJsY2lCUwpiMjkwSUVOQk1CNFhEVEl6TURJeU5ERXdNamt6TmxvWERUSXpNREl5TlRFd01qa3pObG93TWpFVE1CRUdBMVVFCkNnd0tSMkYwWld0bFpYQmxjakViTUJrR0ExVUVBd3dTUjJGMFpXdGxaWEJsY2lCU2IyOTBJRU5CTUlJQklqQU4KQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeUJHZWxtMnZFVnhjVTFtWWlVVW8zdmlRMnUzUQpjS0dZUFRvZUtYQXgwc0Y5Skh4ZWN3MjZPeVBITUtKaFJIZysxcTY3dEhKcGFXVmEzaldjK211Q0ZHbzVVWG9MCmM1M2NOc1BYTm9nc2xmditjS0JWbEN0SW1SM2gyWDBxem9LYnl2cTNHT21ZS3FuN0pyc1hwVkh4K3lCWDdmbWgKRjROZ1NTTmlpU2RLdFdqdng2RFlMWVdXRG1kSXVWdVZld0hSRTZyK0FKS01zTTM0SjhtMkVvblRKLzc3bzZiSQp6bXAxQmk2Q240bGpnK2YzeEc4NkVWZGNOanIwaUhvOWJPY2lXTDIxVldaYldFc3RwM0RLeXBSZ1NkNnkxU0NQCmNoUExGaFJZRUhZelE3a3RBdWxIRXZNclFZZXlZYkRYeWxybGN0U0lyL1Y3Z2NqTjdNamplaC8xOHdJREFRQUIKbzFNd1VUQWRCZ05WSFE0RUZnUVUramhxNHdrZUUyWXR1UDd4bnI0TGw2bGFONDR3SHdZRFZSMGpCQmd3Rm9BVQoramhxNHdrZUUyWXR1UDd4bnI0TGw2bGFONDR3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQVFFQWlaSFdDRjJQTHgvNHEzR0dIWTBWdzk3TjlyTVZCY3o3bzUwQVpScUNTMGVlaW11ZTk4a0IKUXlhVzRiUXhDMXJlZTRrK2pzYXVjTWI5VmJvcTJ6SW1kUlVIYmdtYkgrS3BIUy9RaUNvVTdRMHM0UEhDRll5VgpPQkVKMFZJdkNldzFNcnp6K1d6WVllSlpRMkx4WWVZNndQY1RxdUFreEVkQUNVZjNMbFBHZVVKaG43MHAydlg1CmFMVlJYUUpIMDJ6SG9UNHlyVGxnV0JxbWxCRWlaZzVXVngxTVBYeFNXVFpCQS9tdTJFdFdJWkJNZFlGbnhkckIKU1RKSnNSTlowNGdDa3hwUytYbkE4RDJ2MTJRdzJMZ0N1YWhLNkFoc0NLQ2RTY1E2NnJKcUQ2L0kvWXZkN1FhcwpqclBPV1lXbGo0RFhERmZQL0tQdWNlTUpkbmQ3akdwdWl3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  timeout: 1
  url: https://external-data-provider.gatekeeper-system:8090
