apiVersion: constraints.gatekeeper.sh/v1beta1
kind: HostIPC
metadata:
  name: hostipc-should-be-false
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
  parameters:
    labels: ["gatekeeper"]
